// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzAKHH4UI_LxKSeeb8ObUTxZ_RNt-G7AI',
    appId: '1:432670175669:web:0e58a77ebe4791c477e9fc',
    messagingSenderId: '432670175669',
    projectId: 'lnastaqim',
    authDomain: 'lnastaqim.firebaseapp.com',
    storageBucket: 'lnastaqim.firebasestorage.app',
    measurementId: 'G-T8ERX4XFHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYXb3rBdXRzu7ayN3krDhLQ6TQfyTyBOA',
    appId: '1:432670175669:android:94ff1f53b6c2084077e9fc',
    messagingSenderId: '432670175669',
    projectId: 'lnastaqim',
    storageBucket: 'lnastaqim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFvh1d7FbWQorp8ajI-IWKeT89GRWyREY',
    appId: '1:432670175669:ios:ac06c70cedb3da8477e9fc',
    messagingSenderId: '432670175669',
    projectId: 'lnastaqim',
    storageBucket: 'lnastaqim.firebasestorage.app',
    iosBundleId: 'com.islam.lnastaqim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFvh1d7FbWQorp8ajI-IWKeT89GRWyREY',
    appId: '1:432670175669:ios:960de84d52f527af77e9fc',
    messagingSenderId: '432670175669',
    projectId: 'lnastaqim',
    storageBucket: 'lnastaqim.firebasestorage.app',
    iosBundleId: 'com.example.lnastaqim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzAKHH4UI_LxKSeeb8ObUTxZ_RNt-G7AI',
    appId: '1:432670175669:web:a9110a1c4f76855677e9fc',
    messagingSenderId: '432670175669',
    projectId: 'lnastaqim',
    authDomain: 'lnastaqim.firebaseapp.com',
    storageBucket: 'lnastaqim.firebasestorage.app',
    measurementId: 'G-8Z57B37W40',
  );
}
