include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore

linter:
  rules:
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    await_only_futures: true
    camel_case_types: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    file_names: true
    no_duplicate_case_values: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_string_interpolations: true
    use_key_in_widget_constructors: true
