name: lnastaqim
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.15+1

environment:
  sdk: ">=3.2.6 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  adhan: ^2.0.0+1
  alarm: ^3.0.3
  android_alarm_manager_plus: ^3.0.1
  audio_service: ^0.18.16
  audioplayers: ^4.0.0
  cached_network_image: 3.3.1
  carousel_slider: ^5.0.0
  collection: ^1.18.0
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_local_notifications: null
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: 2.3.7
  flutter_qiblah: ^2.1.0
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.1.1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.9
  flutter_timezone: ^1.0.8
  flutter_tts: ^3.8.5
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.4.1
  geolocator: ^9.0.2
  get: ^4.6.1
  get_it: ^8.0.3
  go_router: ^10.1.2
  google_maps_flutter: ^2.5.3
  hijri: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.6
  internet_connection_checker: ^1.0.0+1
  intl: any
  lottie: 3.0.0
  meta: ^1.10.0
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3
  permission_handler: ^11.1.0
  radio_player: ^1.6.0
  retrofit: ">=4.0.0 <5.0.0"
  screenshot: ^3.0.0
  scroll_screenshot: ^0.0.4
  share_plus: ^9.0.0
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.2.0+3
  table_calendar: ^3.1.2
  timezone: ^0.9.4
  uni_links3: ^0.5.3
  url_launcher: ^6.2.4
  workmanager: null

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  intl_translation: ^0.20.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/svgs/

    - assets/svgs/flags/

    - assets/svgs/surah_name/
    - assets/svgs/bookmark.svg
    - assets/json/animations/
    - assets/images/sibha.png
    - assets/images/notification_largeIcon.png
    - assets/images/notification_bigPicture.png
    - assets/sounds/
    - assets/sounds/notification_and_alarms/
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example: assets/fonts/thuluth-decorated.ttf      ...
  fonts:
    - family: Mushaf
      fonts:
        - asset: assets\fonts\Al Mushaf Quran.ttf
    - family: Naskh
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-VariableFont_wght.ttf
    - family: Thuluth
      fonts:
        - asset: assets/fonts/thuluth-decorated.ttf
    - family: Amiri
      fonts:
        - asset: assets\fonts\Amiri.ttf

    - family: Majeed
      fonts:
        - asset: assets/fonts/Al Majeed Quranic Font_shiped.ttf

    - family: Arab140
      fonts:
        - asset: assets/fonts/ArabQuranIslamic140-7BG9A.ttf
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/me_quran Regular.ttf

    - family: Authmanic
      fonts:
        - asset: assets/fonts/UthmanicHafs_V20.ttf
    - family: Basmala
      fonts:
        - asset: assets/fonts/QCF_BSML.ttf
    #   - asset: fonts/TrajanPro_Bold.ttf
    #     weight: 700
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
    # assets/fonts/UthmanicHafs1B Ver13.ttf assets/fonts/QCF_BSML.ttf
