import 'package:hive/hive.dart';

part 'reciters_model.g.dart'; // This will be generated by Hive generator

@HiveType(typeId: 4) // Unique typeId for this class
class Reciter extends HiveObject {
  @HiveField(0)
  final int id;
  
  @HiveField(1)
  final String name;
  
  @HiveField(2)
  final String nameArabic;
  
  @HiveField(3)
  final String nationality;

  Reciter({
    required this.id,
    required this.name,
    required this.nameArabic,
    required this.nationality,
  });

  factory Reciter.fromJson(Map<String, dynamic> json) {
    return Reciter(
      id: json['id'],
      name: json['name'],
      nameArabic: json['name_arabic'],
      nationality: json['nationality'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'name_arabic': nameArabic,
      'nationality': nationality,
    };
  }
}