default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  
  lane :android_lnastaqim_prod do
    sh "flutter clean"
    sh "flutter build apk --release --flavor lnastaqim_prod -t lib/main_lnastaqim_prod.dart --build-name=1.1.3.0 --build-number=2 --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:432670175669:android:807ef8fd76fc7ed577e9fc",
      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-lnastaqim_prod-release.apk",
      groups: "lnastaqim",
      release_notes:"(lnastaqim prod app)",
      upload_timeout: 600
    )
  end




    lane :android_lnastaqim_dev do
    firebase_app_distribution(
      app: "1:432670175669:android:94ff1f53b6c2084077e9fc",
      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-lnastaqim_dev-release.apk",
      groups: "lnastaqim",
      release_notes:"(lnastaqim prod app)",
      upload_timeout: 600
    )
  end
  
end
