name: Flutter CI/CD with Fastlane 

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.3"

      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5' 
          bundler-cache: true
          working-directory: android


      - name: Install bundle
        run: |
            cd android   # Change directory to the android directory where Gemfile is located
            bundle config path vendor/bundle   # Configure Bundler to use vendor/bundle directory
            bundle install --jobs 4 --retry 3 # Install gems specified in Gemfile
            
      - name: Set environment variables from secrets
        run: |
            echo "FIREBASE_APP_ID=${{ secrets.APP_ID }}" >> $GITHUB_ENV
            echo "FIREBASE_TOKEN=${{ secrets.FIREBASE_CLI_TOKEN }}" >> $GITHUB_ENV
  
  
      - name: Add Firebase App Distribution Plugin
        run: |
            cd android
            bundle exec fastlane add_plugin firebase_app_distribution
      - name: Fastlane Firebase Distribution
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane firebase_distribution
        working-directory: android
